Edited Mentee's link in mentorship page table
chaoss/website pull request #596
Opened 2021-04-03 15:21 UTC by robin025

Fixes #585 
hey @GeorgLink  and @klumb 
actually I had a discussion with @klumb   on issue #585, so I have decided to add **#user-content** keyword before every mentee's link so that it can redirect user to that section

2021-04-06 15:17 UTC, klumb commented
This looks good, but can you remove any edits to the CHAOSScon pages. I think they should be archived the way they are.

2021-04-06 16:04 UTC, robin025 commented
Actually @klumb I have already reverted all the changes in CHAOSScon pages that i have created and @GeorgLink  have merged that PR #590

2021-04-07 16:50 UTC, vchrombie requested changes
stumbled upon this

2021-04-07 16:51 UTC, vchrombie requested changes

2021-04-07 16:51 UTC, vchrombie commented on Community/alumni.md
> +|[Saicharan Reddy](#Suser-content-aicharan-Reddy)|GSoC 2020|Implementation of GitLab Data Collection Worker & Test Coverage Improvement|Elita Nelson, Sean Goggins, Jonahz|
oops, a typo

2021-04-10 05:27 UTC, robin025 commented on Community/alumni.md
> +|[Saicharan Reddy](#Suser-content-aicharan-Reddy)|GSoC 2020|Implementation of GitLab Data Collection Worker & Test Coverage Improvement|Elita Nelson, Sean Goggins, Jonahz|
Done... @vchrombie, fixed the typo

2021-04-12 18:14 UTC, klumb commented
Is this ready to merge? @vchrombie

2021-04-12 19:42 UTC, vchrombie commented
Thanks @robin025 for the work.
Sorry @klumb, I missed the notification. Let me check it once again.

2021-04-12 19:43 UTC, vchrombie approved these changes
LGTM! I hope the changes would fix the scrolling issue.

2021-04-13 15:08 UTC, merged

2021-04-13 15:20 UTC, klumb commented
Hi, @robin025 I merged this but it does not fix the scrolling issue.

For this to work, the URL link needs to be lower case.


For example:
[Jaskirat Singh](#user-content-jaskirat-singh)
https://chaoss.community/chaoss-mentorship/#user-content-jaskirat-singh

If you go back and make all the names in the link lower case it should work.

2021-04-13 15:38 UTC, robin025 commented
> Hi, @robin025 I merged this but it does not fix the scrolling issue.
> 
> For this to work, the URL link needs to be lower case.
> 
> For example:
> [Jaskirat Singh](#user-content-jaskirat-singh)
> https://chaoss.community/chaoss-mentorship/#user-content-jaskirat-singh
> 
> If you go back and make all the names in the link lower case it should work.


okay.. @klumb